-- CREATE TABLE region (
-- id INTEGER,
-- name VARCHAR(80));
-- CREATE TABLE province (
-- id INTEGER,
-- province_id INTEGER,
-- name VARCHAR(80));
-- CREATE TABLE depository(
-- id INTEGER,
-- depository_id INTEGER,
-- name VARCHAR(80),
-- adress VARCHAR(80),
-- year_of_foundation INTEGER,
-- quantity INTEGER
-- );
-- CREATE TABLE output (depository_id INTEGER,oil_per_day FLOAT, date
-- DATE);
-- ALTER TABLE region ADD PRIMARY KEY (id);
-- ALTER TABLE province ADD PRIMARY KEY (id);
-- ALTER TABLE province ADD CONSTRAINT cs_province FOREIGN
-- KEY(province_id) REFERENCES region(id);
--  ALTER TABLE depository ADD PRIMARY KEY (id);
--  ALTER TABLE depository ADD CONSTRAINT cs_depository FOREIGN KEY
-- (depository_id) REFERENCES province(id);
--  ALTER TABLE output ADD CONSTRAINT cs_output FOREIGN
-- KEY(depository_id) REFERENCES depository(id);
-- create SEQUENCE setid minvalue 0;
-- ALTER TABLE region ALTER id SET DEFAULT nextval('setid');
-- INSERT INTO region (id,name) VALUES(1,'Дніпровсько-Донецький
-- регіон');
-- INSERT INTO region (id,name) VALUES(2,'Передкарпатський регіон');
-- INSERT INTO province (id,province_id,name) VALUES(1,1,'Херсонська');
-- INSERT INTO province (id,province_id,name) VALUES(2,1,'Полтавська');
-- INSERT INTO province (id,province_id,name)
-- VALUES(3,1,'Дніпропетровська');
-- INSERT INTO province (id,province_id,name) VALUES(4,1,'Сумська');

-- INSERT INTO province (id,province_id,name) VALUES(5,2,'Івано-
-- Франківська');

-- INSERT INTO province (id,province_id,name) VALUES(6,2,'Львівська');
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(1,1,'Каховське-Н','5 км на ПнС вiд м. Херсон',1990,12);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(2,2,'Хорольське-НГК','9 км на ПдС вiд м. Кобеляки',1964,25);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(3,3,'Могильське-НГ','3 км вiд м. Hoвомосковськ',1976,43);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(4,3,'Роздорівське-НГК','21 км на ПнЗ вiд с. Іскра',1985,23);

-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(5,4,'Левадівське-НГК','100 км на ПнС вiд м. Ромни',1973,35);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(6,4,'Корецьке-НГК','50 км на ПнЗ вiд м. Ромни',1990,64);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)

-- VALUES(7,5,'Коломийське-Н','60 км на П вiд м. Iв-
-- Фpанкiвськ',1956,34);

-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)

-- VALUES(8,5,'Калуське-НГК','30 км на З вiд м. Iв-
-- Фpанкiвськ',1962,37);

-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)

-- VALUES(9,5,'Тлумацьке-Н','7 км на ПдС вiд м. Iв-
-- Фpанкiвськ',1967,35);

-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(10,6,'Ходорівське-НГК','10 км на ПдЗ вiд м. Львів',1954,45);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(11,6,'Глинянське-Н','20 км на ПдЗ вiд м. Бібрка',1967,22);
-- INSERT INTO
-- depository(id,depository_id,name,adress,year_of_foundation,quantity)
-- VALUES(12,6,'Стрийське-Н','15 км на ПдЗ вiд м. Стрий',1890,18);

-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (1,6120,'2005-09-12');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (1,970,'2007-05-04');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (1,630,'2009-03-16');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (1,712,'2011-12-07');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (2,58766,'2005-08-03');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (2,2250,'2005-10-16');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (2,5634,'2006-10-17');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (2,6783,'2006-12-14');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (3,4590,'2005-12-17');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (3,9761,'2009-06-21');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (4,3050,'2005-12-07');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (4,4678,'2007-11-12');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (5,6787,'2009-03-07');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (5,6989,'2010-08-04');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (5,8094,'2011-04-12');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (6,31575,'2005-05-28');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (6,84161,'2006-11-22');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (6,112301,'2007-04-29');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (7,28459,'2010-12-11');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (7,35678,'2012-11-10');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (8,7108,'2007-12-23');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (8,9567,'2009-10-01');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (9,9164,'2005-09-17');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (9,1784,'2007-07-19');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (9,3098,'2009-03-07');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (9,5621,'2011-11-23');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (10,59025,'2003-01-29');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (10,72654,'2006-10-17');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (10,65314,'2009-05-14');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (11,1934,'2008-02-28');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (11,2643,'2010-07-12');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (12,4527,'2005-09-22');
-- INSERT INTO output (depository_id,oil_per_day,date) VALUES (12,9472,'2007-11-13');

-- SELECT * FROM depository,region;
-- SELECT * FROM output,depository WHERE (oil_per_day>=9500 AND
-- oil_per_day<=11000) AND (quantity>=20 AND quantity<=25);